dk_user:
    resource: "@DkUserBundle/Controller/"
    type:     annotation
    prefix:   /

dk_app:
    resource: "@DkAppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"